version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:${MSSQL_VERSION}
    restart: always
    ports:
      - ${MSSQL_PORT}:1433
    environment:
      - ACCEPT_EULA=${MSSQL_ACCEPT_EULA}
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
    volumes:
      - ${MSSQL_VOLUME}:/var/opt/mssql
    networks:
      - mssql
  api:
    image: charustaadam95/smart-fridge-manager-api:${API_VERSION}
    restart: always
    ports:
      - ${API_PORT}:80
    depends_on:
      - mssql
    networks:
      - mssql
      - api
  gui:
    image: charustaadam95/smart-fridge-manager-gui:${GUI_VERSION}
    restart: always
    depends_on:
      - api
    ports:
      - ${GUI_PORT}:80
    networks:
      - api

volumes:
  mssql_data:
    driver: local

networks:
  mssql:
    driver: bridge
  api:
    driver: bridge