version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:${MSSQL_VERSION}
    container_name: mssql_dev
    restart: always
    ports:
      - ${MSSQL_PORT}:1433
    environment:
      - ACCEPT_EULA=${MSSQL_ACCEPT_EULA}
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
    volumes:
      - ${MSSQL_VOLUME}_dev:/var/opt/mssql
    networks:
      - mssql
  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis_dev
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${REDIS_VOLUME}_dev:/data
    networks:
      - redis
  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    container_name: rabbitmq_dev
    restart: always
    ports:
      - ${RABBITMQ_API_PORT}:5672
      - ${RABBITMQ_UI_PORT}:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ${RABBITMQ_VOLUME}_dev:/var/lib/rabbitmq
    networks:
      - rabbitmq
  workers:
    build:
      context: ./repositories/SmartFridgeManagerWorkers
    container_name: workers_dev
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=${WORKERS_ASPNETCORE_ENVIRONMENT}
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=${RABBITMQ_API_PORT}
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ${WORKERS_LOGS_PATH}_dev:/logs
    depends_on:
      - rabbitmq
      - api
    networks:
      - rabbitmq
  api:
    build:
      context: ./repositories/SmartFridgeManagerAPI
    container_name: api_dev
    restart: always
    ports:
      - ${API_PORT}:80
    environment:
      - ASPNETCORE_ENVIRONMENT=${API_ASPNETCORE_ENVIRONMENT}
      - DB_HOSTNAME=mssql
      - DB_PORT=${MSSQL_PORT}
      - DB_USER=${MSSQL_SA_USER}
      - DB_PASS=${MSSQL_SA_PASSWORD}
      - DB_NAME=${MSSQL_DATABASE_NAME}
      - DB_OPTIONS=${MSSQL_OPTIONS}
      - JWT_KEY=${API_JWT_KEY}
      - JWT_EXPIRE_DAYS=${API_JWT_EXPIRE_DAYS}
      - JWT_ISSUER=${API_JWT_ISSUER}
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=${RABBITMQ_API_PORT}
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ${API_LOGS_PATH}_dev:/logs
    depends_on:
      - mssql
      - rabbitmq
      - redis
    networks:
      - rabbitmq
      - redis
      - mssql
      - api
  gui:
    build:
      context: ./repositories/SmartFridgeManagerGUI
    container_name: gui_dev
    restart: always
    depends_on:
      - api
    ports:
      - ${GUI_PORT}:80
    networks:
      - api

volumes:
  mssql_data_dev:
    driver: local
  rabbitmq_data_dev:
    driver: local
  redis_data_dev:
    driver: local
  api_logs_dev:
    driver: local
  workers_logs_dev:
    driver: local

networks:
  mssql:
    driver: bridge
  api:
    driver: bridge
  rabbitmq:
    driver: bridge
  redis:
    driver: bridge
