version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:${MSSQL_VERSION}
    container_name: mssql_dev
    restart: always
    ports:
      - ${MSSQL_PORT}:1433
    environment:
      - ACCEPT_EULA=${MSSQL_ACCEPT_EULA}
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
    volumes:
      - ${MSSQL_VOLUME}_dev:/var/opt/mssql
    networks:
      - mssql
  api:
    build:
      context: ./repositories/SmartFridgeManagerAPI
    container_name: api_dev
    restart: always
    ports:
      - ${API_PORT}:80
    environment:
      - ASPNETCORE_ENVIRONMENT=${API_ASPNETCORE_ENVIRONMENT}
    depends_on:
      - mssql
    networks:
      - mssql
      - api
  gui:
    build:
      context: ./repositories/SmartFridgeManagerGUI
    container_name: gui_dev
    restart: always
    depends_on:
      - api
    ports:
      - ${GUI_PORT}:80
    networks:
      - api

volumes:
  mssql_data_dev:
    driver: local

networks:
  mssql:
    driver: bridge
  api:
    driver: bridge
