version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:${MSSQL_VERSION}
    container_name: mssql
    restart: always
    ports:
      - ${MSSQL_PORT}:1433
    environment:
      - ACCEPT_EULA=${MSSQL_ACCEPT_EULA}
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
    volumes:
      - ${MSSQL_VOLUME}:/var/opt/mssql
    networks:
      - mssql
  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${REDIS_VOLUME}:/data
    networks:
      - redis
  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    container_name: rabbitmq
    restart: always
    ports:
      - ${RABBITMQ_API_PORT}:5672
      - ${RABBITMQ_UI_PORT}:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ${RABBITMQ_VOLUME}:/var/lib/rabbitmq
    networks:
      - rabbitmq
  workers:
    image: charustaadam95/smart-fridge-manager-workers:${WORKERS_VERSION}
    container_name: workers
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=${WORKERS_ASPNETCORE_ENVIRONMENT}
    volumes:
      - ${WORKERS_LOGS_PATH}:/logs
    depends_on:
      - rabbitmq
      - api
    networks:
      - rabbitmq
  api:
    image: charustaadam95/smart-fridge-manager-api:${API_VERSION}
    container_name: api
    restart: always
    ports:
      - ${API_PORT}:80
    environment:
      - ASPNETCORE_ENVIRONMENT=${API_ASPNETCORE_ENVIRONMENT}
    volumes:
      - ${API_LOGS_PATH}:/logs
    depends_on:
      - mssql
      - rabbitmq
      - redis
    networks:
      - rabbitmq
      - redis
      - mssql
      - api
  gui:
    image: charustaadam95/smart-fridge-manager-gui:${GUI_VERSION}
    container_name: gui
    restart: always
    depends_on:
      - api
    ports:
      - ${GUI_PORT}:80
    networks:
      - api

volumes:
  mssql_data:
    driver: local
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local
  api_logs:
    driver: local
  workers_logs:
    driver: local

networks:
  mssql:
    driver: bridge
  api:
    driver: bridge
  rabbitmq:
    driver: bridge
  redis:
    driver: bridge
